#!/bin/bash

hostn=$(cat /etc/hostname)

echo "Existing hostname is $hostn"

while getopts n: option
do
    case "${option}"
    in
        n) $newhost=${OPTARG};;
    esac
done

hostnamectl set-hostname $newhost
sudo sed -i "s/localhost/$newhost/g" /etc/hosts


#display new hostname
echo "Your new hostname is $newhost"

sudo reboot
